# /home/daniel/Workspaces/StockShow/pattern-identifier/.pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Updated to latest stable version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 24.8.0 # Updated to latest stable version
    hooks:
    -   id: black
        args: [--line-length=119] # Ensure this matches your pyproject.toml
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2 # Already latest stable
    hooks:
    -   id: isort
        args: ["--profile", "black"] # --filter-files is often redundant with pre-commit
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.0 # Updated to latest stable version
    hooks:
    -   id: flake8
        args: [--max-line-length=119] # Ensure this matches your .flake8
        additional_dependencies: [flake8-bugbear]
